---
- hosts: 127.0.0.1
  connection: local
  gather_facts: true
  become: true
  vars_prompt:
    - name: "prompt_change_ssh"
      prompt: "Replace ssh_config?"
      default: yes
      private: no
    - name: "prompt_ssh_key_pass"
      prompt: "SSH Key Password?"
      default: "W!red312"
      private: yes
    - name: "prompt_ssh_key_file"
      prompt: "SSH Key File?"
      default: "hephaestus"
      private: yes
    
  roles:
    - ssh_config
    - collect_janus
    - collect_hephaestus
#- import_playbook: ../../Hephaestus/Ansible/Launchpad/play_local_launchpad.yaml
#- import_playbook: ../../Hephaestus/Ansible/Launchpad/play_local_gantry.yaml